### ISSUE TITLE
Update Javaassist

### ISSUE THREAD

**Issue by PixelBumper** [inspire-software/geda-genericdto#1]
We ran into the following exception:

```
UnableToCreateInstanceException: Unable to instantiate class:
...
Caused by: java.lang.RuntimeException: java.io.IOException: invalid constant type: 18
... 
```

![image](https://cloud.githubusercontent.com/assets/14896972/14310465/3ee37462-fbe2-11e5-89be-1ff7120eb222.png)

this is due to an outdated javaassist version.
we added version 3.19 to our project

```
compile 'org.javassist:javassist:3.19.0-GA'
compile("com.inspire-software.lib.dto.geda:geda.core:$gedaVersion") {
    exclude module: 'slf4j-api'
    exclude group: 'javassist', module: 'javassist'
}
```

PS: Is there some introduction for GeDA developers? I might be interested in adding a few pull requests.

**Comment by inspire-software** [comment]
Yes, some of the dependency libraries are dated but the idea was that you can just plug'n'play, just as you did by excluding dependency that you do not need and add newer one. Because GeDA is very particular on how is uses byte code generation 3rd party libraries it is rarely that you encounter problems with upgrading them. In essence GeDA only auto creates classes that have simple get/set calls. 

P.S. There is no guide apart from documentation [http://www.inspire-software.com/confluence/display/GeDA/GeDA+-+Generic+DTO+Assembler] but all code is well documented and we are here to answer your questions if you have some. Will be looking forward to pull requests from you.

**Comment by PixelBumper** [comment]
I understand the intent, but this issue is caused by differences in bytecode between java 8 and previous java versions.

People who start a new java 8 project might have difficulties getting started and start to look for alternatives.

Edit: will try to Post a gist tomorrow that Displays the issue

**Comment by inspire-software** [comment]
Yes, true, we need to review some dependencies. If you send a pull request we can repack the release.

**Comment by PixelBumper** [comment]
Any news on this?
Just today I ran into issues because of the old javaassist version, while using reflection to find classes.

It was a tricky to find issue as it was camouflaged by the fact that the Reflections library catches all exceptions on classpath scanning, so the unknown constant type exception was silently swallowed.

I would go as far as to say that currently geda is dangerous to use in newer java versions until a newer version of javassist is used.

**Comment by denyspavlov** [comment]
Hi,

We pushed repacked version 3.1.1 today to maven central with org.javassist:javassist:3.19.0-GA

Let me know how it works out for you.
