### ISSUE TITLE
Allow initialization of immutable DTOs without BeanFactorys

### ISSUE THREAD

**Issue by PixelBumper** [inspire-software/geda-genericdto#2]
Currently it is only possible to initialize immutable objects by using a beanFactory.
It would be much cooler to allow this without having the need to use those.

One way this could be solved is by adding appropriate constructors or setters via bytecode enhancement at runtime.

The following DTO...

``` java
    @Dto
    public class ImmutableDTO {
        @DtoImmutableField
        private String immutableField;

        public String getImmutableField(){
            return immutableField;
        }
    }
```

could be enhanced to this:

``` java
    @Dto
    public class ImmutableDTO {
        @DtoImmutableField
        private String immutableField;

        public String getImmutableField(){
            return immutableField;
        }

        // added via bytecode enhancement. 
        // Matching the fields to the constructor parameters should be possible with java 8 
        // and the new -param compile option
        public ImmutableDTO(String immutableField){
            this.immutableField = immutableField;
        }

        // if it turns out that the constructor approach is not practical,
        // setters could still be added alternatively,
        // although not ideal as obviously the DTO is not really immutable anymore.
        // It would still be acceptable since the developer cannot see them during development.
        public void setImmutablefield(String immutableField){
            this.immutableField = immutableField;
        }
    }
```

**Comment by inspire-software** [comment]
It is a tough question because even your example of immutable object is not immutable. It is possible to use reflection to get field on the class, change modifier to public and set the value. So if someone wants to be naughty they can easily do it. This kind of messes up all your design. If you want truly immutable then you must mark fields as "final" but then you can only set them in the constructor.

The point I am trying to make here is that although you have good intentions to prevent developers from messing around with your DTO's you cannot really stop them as you leave the doorway for direct setting of values to fields.

Now specifically to GeDA philosophy - by design GeDA promises never to mess with internals and it only uses public getters/setters to do its work. This way everything is transparent and easy to debug. So making GeDA pipes set values directly to fields is a "big no no" in terms of the original design.

If we think a little about DTO's - they are suppose to be dull POJO which sole purpose is to transfer data. So it is ok to have them mutable. They do not pose any threat to data integrity (say as domain model objects or business objects with state or sorts).

Now to a better approach of what you were trying to accomplish in my view is. To have interface for DTO that defines only getters. DTO implementation is a POJO with full set of getters and setters. The implementation is retrieved from bean factory so it is easy to code to interface. Thus when you assemble DTO you get interface and therefore "setters are hidden" for developers. But because GeDA "knows" what DTO implementation is it still can use setters. So win-win and no need to use field value injection.
